package com.learn.springcloud.mapper;

import com.learn.springcloud.po.MiniproUser;
import com.learn.springcloud.po.MiniproUserExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface MiniproUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minipro_user
     *
     * @mbg.generated
     */
    long countByExample(MiniproUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minipro_user
     *
     * @mbg.generated
     */
    int deleteByExample(MiniproUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minipro_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minipro_user
     *
     * @mbg.generated
     */
    int insert(MiniproUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minipro_user
     *
     * @mbg.generated
     */
    int insertSelective(MiniproUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minipro_user
     *
     * @mbg.generated
     */
    List<MiniproUser> selectByExample(MiniproUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minipro_user
     *
     * @mbg.generated
     */
    MiniproUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minipro_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MiniproUser record, @Param("example") MiniproUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minipro_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MiniproUser record, @Param("example") MiniproUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minipro_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MiniproUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minipro_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MiniproUser record);
}