spring:
  application:
    name: consul-service
#  profiles:
#    active: dev
  cloud:
    consul:
      # 服务发现配置
      discovery:
        # 启用服务发现
        enabled: true
        # 启用服务注册
        register: true
        # 服务停止时取消注册
        deregister: true
        # 表示注册时使用IP而不是hostname
        prefer-ip-address: true
        # 执行监控检查的频率
        health-check-interval: 30s
        # 设置健康检查失败多长时间后，取消注册
        health-check-critical-timeout: 30s
        # 健康检查的路径
        health-check-path: /actuator/info
        # 服务注册标识，格式为：应用名称+服务器IP+端口
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  zipkin:
    base-url: http://localhost:9411/


server:
  port: 8899

student:
  name: s

#全局配置
# 请求连接的超时时间 默认的时间为 1 秒
ribbon:
  ConnectTimeout: 1000
# 请求处理的超时时间
  ReadTimeout: 1000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 2000
      circuitBreaker:
        requestVolumeThreshold: 2

product:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#feign:
#  hystrix:
#    enabled: true

# 环形队列的大小，默认是26万
# 全异步模式下
AsyncLogger:
    RingBufferSize: 10000
# 混合模式下
AsyncLoggerConfig:
  RingBufferSize: 10000
# 自动降级--丢弃日志
log4j2:
  AsyncQueueFullPolicy: Discard
  # 队列满后丢弃DEBUG级别的日志
  DiscardThreshold: DEBUG
